
files: "./config/mini_accessions.txt"

fastp: 
  walltime: "10-00:00:00"
  threads: 8 
  mem_gb: 120

get_time:
  threads: 1 
  mem_gb: 4

binbench_minimap:
  threads: 1 
  mem_gb: 10

combine_binbench:
  threads: 1 
  mem_gb: 10

vamb_for_strobealign_default:
  threads: 40 
  mem_gb: 100
