files: "./config/accessions.txt"

fastp: 
  walltime: "10-00:00:00"
  threads: 8 
  mem_gb: 120
  
spades: 
  walltime: "15-00:00:00"
  threads: 16 # 16 is default in metaSpades
  mem_gb: 245

SCAPP: 
  walltime: "45-00:00:00"
  threads: 63 
  mem_gb: 990

index:
  threads: 8 
  mem_gb: 120

minimap: 
  walltime: "10-00:00:00"
  threads: 16 
  mem_gb: 245

sort:
  threads: 8 
  mem_gb: 120

align_contigs:
  threads:  8 
  mem_gb: 120

vamb_asymmetric:
  walltime: "05-00:00:00"
  threads: 16 
  mem_gb: 245

run_geNomad:
  walltime: "05-00:00:00"
  threads: 16
  mem_gb: 245


fastq_end: ".fastq.gz"


# Options from pau pipeline
contigs_filtered_file: "/home/projects/ku_00197/people/lasdan/contig_cutoff/vamb_ptracker_done/Gastrointestinal/para_2000/contigs.flt.fna.gz"
abundance_file: "/home/projects/ku_00197/people/lasdan/contig_cutoff/vamb_ptracker_done/Gastrointestinal/para_2000/abundance.npz"
contignames_file: "/home/projects/ku_00197/people/lasdan/contig_cutoff/vamb_ptracker_done/Gastrointestinal/para_2000/1_vamb/contignames"
samples: "S1 S2 S3 S4 S5 S6 S7 S8 S9 S10"
index_size: "3G"
min_contig_len: "2000"
plamb_mem: "150GB"
plamb_ppn: "30"
plamb_params: " -o C --gamma 0.1 -b 200 "
plamb_preload: ""
outdir: "./data"
assembly_graph_dir: "/home/projects/ku_00197/data/ptracker/cache/as_mp_merged_reads_ef/Gastrointestinal/"
renaming_file: "/home/projects/ku_00197/people/paupie/repo/ptracker_2/ptracker/tmp/renaming_files/renamed_Gastrointestinal"
n2v_ed: '32'
n2v_wl: '10'
n2v_ws: '10'
n2v_p: '0.1'
n2v_q: '2.0'


# Old
# Datafiles cuhange
contigs: 
sample_data: 
config_path: 
sample: 
times_run_vamb: 
# Directories
outdir:
vambsrc: /home/people/lasdan/lasdan/vamb_versions/vamb/src/
# Module envs
moduleenvs:
  minimap2: minimap2/2.6
  samtools: samtools/1.17
